# Generated by Django 2.0.2 on 2018-04-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong')], default='wrong', max_length=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=20),
        ),
    ]
